language:
 java
notifications:
  webhooks:
    - http://octopull.rmhartog.me/api/travis/webhook
before_install:
  - "[ \"$BUILD_PR_BRANCH\" = \"true\" ] && git checkout HEAD^2 && echo \"OCTOPULL_SHA=$(git rev-parse HEAD)\"; true"
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4.11
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - mvn install:install-file -Dfile=/usr/local/share/OpenCV/java/opencv-2411.jar -DgroupId=opencv -DartifactId=opencv -Dversion=2.4.11 -Dpackaging=jar
  - cd ../..
env:
  - BUILD_PR_BRANCH=true
  - BUILD_PR_BRANCH=false
matrix:
  allow_failures:
    - env:
      - BUILD_PR_BRANCH=true
after_script:
  - echo "== CHECKSTYLE_RESULT ==" && cat "target/checkstyle-result.xml" && echo "== END_CHECKSTYLE_RESULT =="
  - echo "== PMD_RESULT ==" && cat "target/pmd.xml" && echo "== END_PMD_RESULT =="
  - echo "== FINDBUGS_RESULT ==" && cat "target/findbugsXml.xml" && echo "== END_FINDBUGS_RESULT =="